/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#fab899",
        "primary-fixed-dim": "#adcfb5",
        "outline-variant": "#c2c8c1",
        "surface-container-low": "#dcfbe2",
        "inverse-primary": "#adcfb5",
        "on-tertiary-container": "#c88c70",
        "surface-dim": "#c3e2c9",
        "inverse-surface": "#1c3625",
        "tertiary-container": "#502712",
        "secondary-fixed-dim": "#8ad7a2",
        "secondary-container": "#a6f4bc",
        secondary: "#1d6b40",
        "surface-variant": "#cbead1",
        "primary-container": "#1a3826",
        "on-tertiary-fixed": "#341101",
        outline: "#727972",
        "error-container": "#ffdad6",
        "on-surface-variant": "#424843",
        "on-secondary-container": "#257246",
        tertiary: "#361302",
        "surface-bright": "#e9ffec",
        "surface-container": "#d7f6dc",
        "surface-tint": "#466550",
        background: "#e9ffec",
        "on-secondary-fixed": "#00210e",
        "on-surface": "#062011",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#00522c",
        "surface-container-highest": "#cbead1",
        "tertiary-fixed": "#ffdbcc",
        "on-primary-fixed": "#022111",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "primary-fixed": "#c8ebd1",
        primary: "#1a3826",
        "on-primary-fixed-variant": "#2f4d3a",
        "secondary-fixed": "#a6f4bc",
        surface: "#e9ffec",
        "on-background": "#062011",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#693b24",
        "surface-container-high": "#d1f0d7",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#daf9df",
        "on-primary-container": "#81a28a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-hero": ["64px", { lineHeight: "72px", fontWeight: "800" }],
        "headline-hero-mobile": ["36px", { lineHeight: "44px", fontWeight: "800" }],
      },
      boxShadow: {
        soft: "0 8px 30px rgba(26,56,38,0.08)",
        punch: "0 10px 25px rgba(26,56,38,0.25)",
      },
      animation: {
        "pulse-slow": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};